version: '3'
services:
  db:
    image: mysql
    container_name: mysql_checkpoint8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3313:3306"
    volumes:
      - checkpoint8_data:/var/lib/mysql
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
volumes:
  checkpoint8_data:


