server:
  error:
    include-stacktrace: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3316/auto_dealer
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true

