version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql_checkpoint7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - checkpoint7_data:/var/lib/mysql
volumes:
  checkpoint7_data: