version: '3'
services:
  db:
    image: mysql
    container_name: mysql_checkpoint7
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3311:3306"
    volumes:
      - checkpoint7_data:/var/lib/mysql
      - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
volumes:
  checkpoint7_data:


